name: vishwakarmas
description: A Flutter application for the Vishwakarma community
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  image_picker: ^1.0.4
  pin_code_fields: ^8.0.1
  intl: ^0.19.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.1.14
  path_provider: ^2.1.1
  permission_handler: 12.0.0+1
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  connectivity_plus: ^4.0.2
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/vishwakarma_logo.png
    - assets/icons/
    - assets/translations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
